version: '3'

services:
  cp-api-manager:
    container_name: cp-api
    restart: always
    ports:
      - "10001:3002"
    image: node:16.20.2
    volumes:
      - .:/workspace
    networks:
      lcz-net:
    working_dir: /workspace
    command: ["npm", "run", "start:dev"]
    
  cp-mongodb:
    container_name: cp-mongo
    image: mongo:7.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongolcz001
      MONGO_INITDB_ROOT_PASSWORD: mongopwd001@@
    ports:
      - "10002:27017"
    networks:
      lcz-net:

networks:
    lcz-net: